### ISSUE TITLE
希望ego框架能够新增grpc-gateway功能

### ISSUE THREAD

**Issue by vicnoah** [gotomicro/ego#117]
**Is your feature request related to a problem? Please describe.**
在用grpc时我用到了grpc-gateway,我目前自己写了一个grpc-gatway的ego-componet因为对ego框架部分功能不太熟，实现得不够优雅，希望ego框架官方能够增加此模块
**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by askuy** [comment]
gRPC gateway有多种玩法。
1. 代码层面实现直接将gRPC转成HTTP，做到一个应用里既能提供http也能提供gRPC，做到少写HTTP的代码逻辑。
2. 通过提供一个API接口，接收proto信息，类似于apisix方式，将grpc转成http

**Comment by askuy** [comment]
gRPC gateway有多种玩法。

代码层面实现直接将gRPC转成HTTP，做到一个应用里既能提供http也能提供gRPC，做到少写HTTP的代码逻辑。
通过提供一个API接口，接收proto信息，类似于apisix方式，将grpc转成http

**Comment by askuy** [comment]
gRPC gateway有多种玩法。

* 代码层面实现直接将gRPC转成HTTP，做到一个应用里既能提供http也能提供gRPC，做到少写HTTP的代码逻辑。
* 通过提供一个API接口，接收proto等元数据信息，类似于apisix方式，将grpc转成http：https://github.com/apache/apisix/blob/master/docs/en/latest/plugins/grpc-transcode.md
* 还有一个是类似这种grpc-gateway玩法：https://github.com/grpc-ecosystem/grpc-gateway

看下你需要哪种玩法。

**Comment by sevennt** [comment]
这个可以在框架里面做，也可以在网关里做，后者的优势就是可以支持多语言。

网关里可以基于 gRPC Reflection 来实现，原理可以参考这个：https://github.com/mercari/grpc-http-proxy

**Comment by vicnoah** [comment]
> gRPC gateway有多种玩法。
> 
> * 代码层面实现直接将gRPC转成HTTP，做到一个应用里既能提供http也能提供gRPC，做到少写HTTP的代码逻辑。
> * 通过提供一个API接口，接收proto等元数据信息，类似于apisix方式，将grpc转成http：https://github.com/apache/apisix/blob/master/docs/en/latest/plugins/grpc-transcode.md
> * 还有一个是类似这种grpc-gateway玩法：https://github.com/grpc-ecosystem/grpc-gateway
> 
> 看下你需要哪种玩法。

觉得api网关对于非大型程序还是太重了,并且像kong,apisix等api网关使用grpc代理时使用及配置很复杂,我是觉得是不是可以集成grpc-gateway,grpc-gateway使用buf等工具后使用上挺简单方便的

**Comment by vicnoah** [comment]
> 这个可以在框架里面做，也可以在网关里做，后者的优势就是可以支持多语言。
> 
> 网关里可以基于 gRPC Reflection 来实现，原理可以参考这个：https://github.com/mercari/grpc-http-proxy

api网关对于grpc的配置太复杂,我是觉得用单体程序也可以使用grpc开发,然后用grpc-gateway集成在一起做代理,就可以只写grpc的服务同时支持http协议了

**Comment by askuy** [comment]
> > 这个可以在框架里面做，也可以在网关里做，后者的优势就是可以支持多语言。
> > 网关里可以基于 gRPC Reflection 来实现，原理可以参考这个：https://github.com/mercari/grpc-http-proxy
> 
> api网关对于grpc的配置太复杂,我是觉得用单体程序也可以使用grpc开发,然后用grpc-gateway集成在一起做代理,就可以只写grpc的服务同时支持http协议了

这个是说从代码维度实现grpc gateway吧。

**Comment by vicnoah** [comment]
> > > 这个可以在框架里面做，也可以在网关里做，后者的优势就是可以支持多语言。
> > > 网关里可以基于 gRPC Reflection 来实现，原理可以参考这个：https://github.com/mercari/grpc-http-proxy
> > 
> > api网关对于grpc的配置太复杂,我是觉得用单体程序也可以使用grpc开发,然后用grpc-gateway集成在一起做代理,就可以只写grpc的服务同时支持http协议了
> 
> 这个是说从代码维度实现grpc gateway吧。
> 

是的

**Comment by askuy** [comment]
> > > > 这个可以在框架里面做，也可以在网关里做，后者的优势就是可以支持多语言。
> > > > 网关里可以基于 gRPC Reflection 来实现，原理可以参考这个：https://github.com/mercari/grpc-http-proxy
> > > 
> > > 
> > > api网关对于grpc的配置太复杂,我是觉得用单体程序也可以使用grpc开发,然后用grpc-gateway集成在一起做代理,就可以只写grpc的服务同时支持http协议了
> > 
> > 
> > 这个是说从代码维度实现grpc gateway吧。
> 
> 是的

没问题，代码层面好实现这个。

**Comment by askuy** [comment]
> > > > 这个可以在框架里面做，也可以在网关里做，后者的优势就是可以支持多语言。
> > > > 网关里可以基于 gRPC Reflection 来实现，原理可以参考这个：https://github.com/mercari/grpc-http-proxy
> > > 
> > > 
> > > api网关对于grpc的配置太复杂,我是觉得用单体程序也可以使用grpc开发,然后用grpc-gateway集成在一起做代理,就可以只写grpc的服务同时支持http协议了
> > 
> > 
> > 这个是说从代码维度实现grpc gateway吧。
> 
> 是的
已支持代码层面grpc gateway。https://github.com/gotomicro/ego/pull/122
有个example和unittest

目前暂定为实验性质。还有几个问题要处理
* grpc到http状态码转换
* 系统错误后，框架响应的结构体和业务响应的结构体可能不一样，导致一些问题，要思考这块的设计
* 错误传递，拦截器记录日志未实现

**Comment by askuy** [comment]
> > > > 这个可以在框架里面做，也可以在网关里做，后者的优势就是可以支持多语言。
> > > > 网关里可以基于 gRPC Reflection 来实现，原理可以参考这个：https://github.com/mercari/grpc-http-proxy
> > > 
> > > 
> > > api网关对于grpc的配置太复杂,我是觉得用单体程序也可以使用grpc开发,然后用grpc-gateway集成在一起做代理,就可以只写grpc的服务同时支持http协议了
> > 
> > 
> > 这个是说从代码维度实现grpc gateway吧。
> 
> 是的



已支持代码层面grpc gateway。#122
有个example和unittest

目前暂定为实验性质。还有几个问题要处理

grpc到http状态码转换
系统错误后，框架响应的结构体和业务响应的结构体可能不一样，导致一些问题，要思考这块的设计
错误传递，拦截器记录日志未实现

**Comment by vicnoah** [comment]
> > > > > 这个可以在框架里面做，也可以在网关里做，后者的优势就是可以支持多语言。
> > > > > 网关里可以基于 gRPC Reflection 来实现，原理可以参考这个：https://github.com/mercari/grpc-http-proxy
> > > > 
> > > > 
> > > > api网关对于grpc的配置太复杂,我是觉得用单体程序也可以使用grpc开发,然后用grpc-gateway集成在一起做代理,就可以只写grpc的服务同时支持http协议了
> > > 
> > > 
> > > 这个是说从代码维度实现grpc gateway吧。
> > 
> > 是的
> 
> 
> 
> 已支持代码层面grpc gateway。#122
> 有个example和unittest
> 
> 目前暂定为实验性质。还有几个问题要处理
> 
> grpc到http状态码转换
> 系统错误后，框架响应的结构体和业务响应的结构体可能不一样，导致一些问题，要思考这块的设计
> 错误传递，拦截器记录日志未实现

感谢付出。看了一下实现，和我当时提出的用意有一点不同。我的原用意是把
https://github.com/grpc-ecosystem/grpc-gateway这个当做网关直接替换gin做http接入层的一种方式。并对其进行相关metric，tracing等ego的封装实现，就是将grpc与grpc-gateway进行结合开发

**Comment by askuy** [comment]
> 这个当做网关直接替换gin做http接入层的一种方式。并对其进行相关metric，tracing等ego的封装实现，就是将grpc与grpc-gateway进行结合开发

邮箱多少，我们加个好友聊下需求。

**Comment by vicnoah** [comment]
> > 这个当做网关直接替换gin做http接入层的一种方式。并对其进行相关metric，tracing等ego的封装实现，就是将grpc与grpc-gateway进行结合开发
> 
> 邮箱多少，我们加个好友聊下需求。

1096224934@qq.com
