### ISSUE TITLE
cron task 设计问题

### ISSUE THREAD

**Issue by optimistic9527** [gotomicro/ego#133]
**Is your feature request related to a problem? Please describe.**
根据当前的代码，目前ecron设计上，每个cron task配置一个config后，都会启动一个cron来运行这个job，这样代价是不是有点高？

**Describe the solution you'd like**
大多数业务场景下，任务会根据业务场景归类，希望这里的ecron是一个配置项目支持的是一组task的管理

**Comment by askuy** [comment]
是的。我们认为一个项目不会有太多定时任务，看了下一个cron、一个job，对业务不会有太大影响。之所以这么设计是为了方便控制定时任务的时间、还有分布式锁，粒度可以控制到job。

**Comment by optimistic9527** [comment]
@askuy 在我当前业务场景中，定时任务非常多,基本上都是按照业务类型进行的job分类，一类的job进行一个分布式锁进行控制。我个人认为，cron job进行组的控制更加符合业务需求。如果你也同意，后续我可以提供PR.

**Comment by askuy** [comment]
> @askuy 在我当前业务场景中，定时任务非常多,基本上都是按照业务类型进行的job分类，一类的job进行一个分布式锁进行控制。我个人认为，cron job进行组的控制更加符合业务需求。如果你也同意，后续我可以提供PR.

可以的。不过按cron job，可能会导致配置复杂，需要权衡易用性和配置难度
