### ISSUE TITLE
egin 支持https并且支持双向认证

### ISSUE THREAD

**Issue by optimistic9527** [gotomicro/ego#171]
背景：
在安全场景下，后端服务提供给第三方，或者跟网关的情况下，虽然在网关后面但是需要与第三方或者官网进行双向认证

当前情况: 
egin不支持https并且支持双向认证

**Comment by askuy** [comment]
在ego v0.6.3版本。已经支持https://github.com/gotomicro/ego/blob/v0.6.3/server/egin/config.go#L30

**Comment by askuy** [comment]
> 测试用例后提供PR

可以啊。非常感谢
