### ISSUE TITLE
[doc] some links error in docs 

### ISSUE THREAD

**Issue by orangle** [gotomicro/ego#290]
![image](https://user-images.githubusercontent.com/2696746/168793870-9982274f-7a37-41f1-88ce-5f022031155a.png)
rt

error: https://github.com/gotomicro/ego/tree/master/examples/config/onelineByFileWatch
right: https://github.com/gotomicro/ego/tree/master/examples/config/oneline-by-file-watch

**Comment by askuy** [comment]
已修复。谢谢
