### ISSUE TITLE
build constraints exclude all Go files

### ISSUE THREAD

**Issue by Alfred-Alan** [gotomicro/ego#313]
run demo with quickstart
https://ego.gocn.vip/frame/quickstart/quickstart.html

go mod is 
`github.com/gotomicro/ego@v1.1.6`

when i want to start app
`go run main.go --config=config.toml`

get error

```
package command-line-arguments
        imports github.com/gotomicro/ego
        imports github.com/gotomicro/ego/core/util/xcolor: build constraints exclude all Go files in E:\go\pkg\mod\github.com\gotomicro\ego@v1.1.6\core\util\xcolor
```

switch to 
`github.com/gotomicro/ego@v1.1.5`
this version is ok

**Comment by sevennt** [comment]
@Alfred-Alan try `go get github.com/gotomicro/ego@master` again.
