### ISSUE TITLE
ekafka组件，当kafka挂掉，再重新启动后。服务是没有办法自动连接上kafka的

### ISSUE THREAD

**Issue by songkaiha** [gotomicro/ego#384]
我看ekafka的底层用的是kafka-go，单独使用kafka-go是支持kafka断掉再启动后，服务能够自动连接kafka的。

但是ekafka封装以后，无法服务无法重连kafka

**Comment by sevennt** [comment]
@songkaiha 可以帮忙提到 https://github.com/ego-component/ekafka/issues 么？我们这边再测试验证下看看

**Comment by songkaiha** [comment]
@sevennt 已提

**Comment by askuy** [comment]
https://github.com/ego-component/ekafka/issues/19
