### ISSUE TITLE
go 1.16 embed 特性加载配置 

### ISSUE THREAD

**Issue by cute-angelia** [gotomicro/ego#59]
**Is your feature request related to a problem? Please describe.**

编译后可执行程序，需要配置文件，往往要把配置文件和可执行程序一起放在线上服务器，配置文件内容尤其是sql连接信息，非常敏感

**Describe the solution you'd like**

1.16之后，有了 embed 特性，可以在编译服务过程中过程中，就把配置打包进去， 线上真正只需要一个可执行程序

**Describe alternatives you've considered**

1.16之前，我们是将配置写在一个go文件里面，不是很友好

**Additional context**

期待更好

**Comment by cute-angelia** [comment]
噢， 想了下，还有种解决办法，使用远端配置

```
go run main.go --config="etcdv3://127.0.0.1:2379?key=config-helloword"
```

要不也支持下😄

**Comment by sevennt** [comment]
> **Is your feature request related to a problem? Please describe.**
> 
> 编译后可执行程序，需要配置文件，往往要把配置文件和可执行程序一起放在线上服务器，配置文件内容尤其是sql连接信息，非常敏感
> 
> **Describe the solution you'd like**
> 
> 1.16之后，有了 embed 特性，可以在编译服务过程中过程中，就把配置打包进去， 线上真正只需要一个可执行程序
> 
> **Describe alternatives you've considered**
> 
> 1.16之前，我们是将配置写在一个go文件里面，不是很友好
> 
> **Additional context**
> 
> 期待更好

配置一般与代码分离，通过 embed 将配置打包进二进制，发版的时候就对不同的环境（develop、production）使用不同的配置了。

**Comment by cute-angelia** [comment]
@sevennt 

嗯，对，也不对。。。。可以打包多份配置，内部逻辑区分环境


这个（embed）需求草率了，算了~，

另外：

帮忙解决下 “远程配置” 这个需求， 我把配置都丢 etcd 里面，这样就不用embed了，而且还分布式了。

**Comment by cute-angelia** [comment]
#64
